### ISSUE TITLE
Is the drupal option under create command gone?

### ISSUE THREAD

**Issue by geraldvillorente** [kalabox/kalabox-app-drupal#7]
```
gerald@von-viel:~/Repo/kalabox-app-drupal$ kbox create drupal -- --name="Drupal" -is
Usage: kbox <command> [-- <options>]

Global commands that can be run from anywhere
  apps             Display list of apps.
  config           Display the kbox configuration.
  containers       Display list of all installed kbox containers.
  create       
      pantheon     Creates a Pantheon app.
  update           Run this after you update your Kalabox code.
  version          Display the kbox version.

Options:
  -h, --help     Display help message.                                 [boolean]
  -v, --verbose  Use verbose output.                                   [boolean]
```

**Comment by pirog** [comment]
Yes. It is no longer supported at this time.

On Saturday, October 31, 2015, Gerald Villorente <notifications@github.com>
wrote:

> gerald@von-viel:~/Repo/kalabox-app-drupal$ kbox create drupal -- --name="Drupal" -is
> Usage: kbox <command> [-- <options>]
>
> Global commands that can be run from anywhere
>   apps             Display list of apps.
>   config           Display the kbox configuration.
>   containers       Display list of all installed kbox containers.
>   create
>       pantheon     Creates a Pantheon app.
>   update           Run this after you update your Kalabox code.
>   version          Display the kbox version.
>
> Options:
>   -h, --help     Display help message.                                 [boolean]
>   -v, --verbose  Use verbose output.                                   [boolean]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-app-drupal/issues/7>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by geraldvillorente** [comment]
So if I want to to setup a basic Drupal installation it is not possible because Kalabox only supports Pantheon?

**Comment by pirog** [comment]
As of right now Kalabox only officially supports Pantheon. We are hoping to add additional integrations and possibly stock start states of various apps as soon as we reach a stable beta release. Always important to remember we are still pretty alpha right now so kalabox is not really intended for actual day-to-day usage at this time.

There is an issue floating around about how to add the old kalabox-app-drupal back into kalabox but im not sure if that still applies.
